### ISSUE TITLE
注意如果你有多个Module，请在每个Module的build.gradle文件中apply插件

### ISSUE THREAD

**Issue by WDevaloper** [Mobcase/McImage#73]
variant.allRawAndroidResources 这个方法获取的是打包过程中包括子模块的resource资源，为什么还要在每个模块中 “apply plugin: 'McImage' 呢？

**Comment by owenlongbo** [comment]
当然了你在root 中 apply 就没问题了，但是如果你在一个子module ，apply的root 就在 这个module了
可能跟这个module 没关联的就有问题，所以要apply 两次

**Comment by WDevaloper** [comment]
我觉得只有在正式打包的时候才做压缩，所以只有在App工程或壳工程中使用，而且你是用的又是 `mergeResourcesTask.dependsOn(McImage))` ，所以在打包时资源合并之前 通过 `allRawAndroidResources`方法得到所有资源，当然这一过程是自动完成的。

**Comment by allen-blue** [comment]
子模块packaged_res 生成了webp 但是工程中没有替换 只有app下的res替换了webp
有遇到过吗
