### ISSUE TITLE
能否支持增量压缩，每次全量耗时有点久

### ISSUE THREAD

**Issue by sixangle** [Mobcase/McImage#84]

**Comment by owenlongbo** [comment]
目前是支持的，压缩过的只会check一下

**Comment by owenlongbo** [comment]
因为无法保证两次命名一样的文件内容一样，md5也不能完全保证。

**Comment by sixangle** [comment]
我的意思是，首次压缩过的图片资源生成一个列表文件，可以在config里配置这个文件，下次构建的时候在resource中排除列表文件中的资源，不指定就是全量，这样增量处理速度会优化不少。
