### ISSUE TITLE
构建出错Could not determine the dependencies of task ':app:mergeDebugResources'

### ISSUE THREAD

**Issue by chipssss** [Mobcase/McImage#85]
集成McImage后构建报错如下，去掉后正常。
报错的是app模块依赖的子组件。
Android Gradle Plugin Version 3.6.1, Gradle Version 5.6.4
![image](https://user-images.githubusercontent.com/39876165/150928789-d3b9927b-cc1e-4161-a106-dc8ab0756aef.png)

**Comment by owenlongbo** [comment]
需要在每一个module里面单独apply一下，bytedance同学可以看下抖音的代码接入下
