### ISSUE TITLE
不支持3.0的android gradle plugin吗？

### ISSUE THREAD

**Issue by qianzui** [Mobcase/McImage#9]
编译的时候发现直接跳过了，没看到对图片的压缩输出。

**Comment by smallSohoSolo** [comment]
我看一下

**Comment by yrom** [comment]
3.0.0 的 merge resources 输出变了

**Comment by smallSohoSolo** [comment]
Tip: If you want to use the plugin in gradle3.X.
Please add this line to close aapt2 in gradle.properties

android.enableAapt2=false

**Comment by smallSohoSolo** [comment]
1.0.0 正式支持了 aapt2 请使用1.0.0版本更新
